### ISSUE TITLE
isAuthorized should return true if service is free

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/marketplace#17]
The function `isAuthorized` should true if the service has on active offer with a price of 0.

The signature of function `isAuthorized` must stay the same.
So a loop on all service's offers should be implemented to check if one is free, but only if the sender didn't purchase it already.

https://github.com/mesg-foundation/marketplace/blob/67957121226ca3ac87b1de2d7b3302d996a7c7ba/contracts/Marketplace.sol#L449-L455

**Comment by antho1404** [comment]
what about if there is no offer at all then it's authorized by default. If there is an offer then you need to purchase. Like that we could have totally free and accessible services and also free but that requires "signup"

**Comment by krhubert** [comment]
few more questions:

- can service have multiple offers with price 0 or only one is allowed?
- should marketplace provide an option to buy offer with price 0 only once (for example someone can buy first free month but only once)
- does the user need to buy free offer?

**Comment by krhubert** [comment]
Done in https://github.com/mesg-foundation/marketplace/commit/6f4602d150ef988a4051a329b793c769b761d1b4

**Comment by NicolasMahe** [comment]
> what about if there is no offer at all then it's authorized by default
I like this! But it's should be: if there is no active offer, then it's authorized by default.
