### ISSUE TITLE
fixed solidity version (minor)

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/marketplace#4]
I'd go with defining the exact version for solidity instead of putting a version range. We never know that a new version (even a minor) will have bugs or not...

https://github.com/mesg-foundation/marketplace/blob/e4840cf/contracts/Marketplace.sol#L1

**Comment by krhubert** [comment]
https://solidity.readthedocs.io/en/v0.5.3/layout-of-source-files.html

Read the note:

>Using the version pragma will not change the version of the compiler. It will also not enable or disable features of the compiler. It will just instruct the compiler to check whether its version matches the one required by the pragma. If it does not match, the compiler will issue an error.

So it's just to tell which version contract is compatible with (also during import of contracts).

So ti's ok to have range between 0.5 < 0.6 as this gurantee that the syntax won't change.
