### ISSUE TITLE
Add test on token smart contract in constructor

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/marketplace#5]
Will be nice to add a test in the constructor of the Marketplace to check if the given token address is really an ERC20

**Comment by krhubert** [comment]
It's not possible at the moment. constructor receives an address of smart contract and constructor will have to call every IERC20 function. The ERC165 solved this pbm by defining [constant](https://ethereum.stackexchange.com/questions/30556/how-to-check-if-a-contract-has-a-method).
